# Playbook for installing the EESSI compatibility layer.
---
- name: Install compatibility layer
  hosts: localhost
  environment:
    PATH:
      "{{ gentoo_prefix_path }}/usr/sbin\
      :{{ gentoo_prefix_path }}/usr/bin\
      :{{ gentoo_prefix_path }}/sbin\
      :{{ gentoo_prefix_path }}/bin\
      :{{ ansible_env.PATH }}"
    EPREFIX: "{{ gentoo_prefix_path }}"
    BPREFIX: "{{ gentoo_prefix_path }}"
    LC_ALL: C
  roles:
    - role: compatibility_layer
    - role: lnx-ar-roche-certificates ### added to mime RoCS
      tags:
        - certs

    
  vars:
   ## add here the variables to be modified for rocs
